import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/src/components/header";
import { Footer } from "@/src/components/footer";

export const metadata: Metadata = {
  title: "Mon portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className="max-w-5xl mx-auto pr-9 pl-9 bg-white dark:bg-neutral-900">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
